tests: Moving providers test to test folder

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,7 @@
-pnpm lint
-pnpm test
+pnpm pre-commit || {
+  echo ''
+  echo '===================================================='
+  echo 'pre-commit checks failed.
+  echo '===================================================='
+  exit 1
+}
